#!/bin/sh
#
# forever      Start up node server daemon
#
# chkconfig: 345 88 08
# description: Forever for Node.js

FOREVER=/usr/bin/node/bin/forever
DEAMON=/home/www/jsgen/app.js
LOG=/home/www/jsgen/mylogs/forever.log
PID=/root/.forever/pids/forever.pid

case "$1" in
    start)
        $FOREVER start -l $LOG --pidFile $PID -a $DEAMON
        ;;
    stop)
        $FOREVER stop --pidFile $PID $DEAMON
        ;;
    stopall)
        $FOREVER stopall --pidFile $PID
        ;;
    restartall)
        $FOREVER restartall --pidFile $PID
        ;;
    reload|restart)
        $FOREVER restart -l $LOG --pidFile $PID -a $DEAMON
        ;;
    list)
        $FOREVER list
        ;;
    *)
        echo "Usage: /etc.init.d/node {start|stop|restart|reload|stopall|restartall|list}"
        exit 1
        ;;
esac
