module.exports = {
    dbErr: '数据库错误',
    UidNone: '用户Uid不存在',
    userNameNone: '用户名不存在',
    userNameErr: '用户名格式错误',
    userNameExist: '用户名已存在',
    userEmailNone: 'Email不存在',
    userEmailErr: 'Email格式错误',
    userEmailExist: 'Email已存在',
    userPasswd: '密码错误',
    userNeedLogin: 'need login',
    userLocked: '用户已被锁定',
    userRoleErr: 'quan xian bu gou',
    resetpwdKey: 'resetpwdKey',
    resetInvalid: 'resetInvalid',
    resetOutdate: 'resetOutdate',
    loginAttempts: '登录失败超过5次，用户被锁定',
    logNameErr: '该用户不存在，请使用用户名、用户邮箱或用户UID登录',
    tagNone: 'tagNone',
};
